services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv
    restart: unless-stopped
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
    environment:
      - PUBLIC_PORT=8899
      - NGINX_HTTP_PORT=8888
    volumes:
      - ./config:/iptv-api/config
      - ./result:/iptv-api/output
    network_mode: host
